# This cnofig specifies the benchmarking client'S behavior

## Where to reach the SUT
sut_address: host.docker.internal
sut_port_write: 50051
sut_port_read: 50052

## How to connect to the SUT
prink_docker_image: "ghcr.io/louisloechel/prink-v2:main"

# Memory for the taskmanager
taskmanager_memory: 8gb

## How to report the results
output_folder: "../results"

## Input Data for the benchmark
input_data: "total.csv"
