# This cnofig specifies the benchmarking client'S behavior

## Where to reach the SUT
sut_address: localhost
sut_port_write: 50051
sut_port_read: 50052

## How to generate the load
mode: "fixed" # "fixed" or "max"
interval: 1 # in seconds
duration: 10 # in seconds (e.g., 900 for 15 minutes)
warmup: 5 # in seconds (e.g., 300 for 5 minutes)

## How to report the results
output_folder: "../results"

## Input Data for the benchmark
input_data: "../data/total.csv"
