
version: "3"

services:
  client:
    build: .
    volumes:
      - ./prometheus:/app/prometheus
      - ../results:/results
    tty: true
    environment:
      CLIENT_CONFIG: |
        # This cnofig specifies the benchmarking client'S behavior

        ## Where to reach the SUT (start)
        sut_port_write: 50051
        sut_port_read: 50052
        local_address: "host.docker.internal"

        # sut addresses
        sut_addresses:
          - host.docker.internal

        sut_docker_host_template: "tcp://{{.Address}}:2375"


        ## How to connect to the SUT
        prink_docker_image: "ghcr.io/louisloechel/prink-v2:main"

        # Memory for the taskmanager
        taskmanager_memory: 2gb

        ## How to report the results
        output_folder: "../results"

        ## Input Data for the benchmark
        input_data: "total.csv"

    ports:
      - "50051-50100:50051-50100"

  # prometheus and grafana for monitoring
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - 9090:9090
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus:/etc/prometheus

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  victoriametrics:
    image: victoriametrics/victoria-metrics
    command:
      - '-promscrape.config=/prometheus/prometheus.yml'
      - '-promscrape.config.strictParse=false'
      - '-retentionPeriod=10y'
    ports:
      - 8428:8428
    restart: unless-stopped
    volumes:
      - ./prometheus:/prometheus:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
